'use strict';
module.exports = {
  up: (queryInterface, Sequelize) => {
    return queryInterface.bulkInsert('Photos', [
    {
     userId: 1,
     locationId: null,
     imgURL: 'https://touristrbucket.s3.us-west-1.amazonaws.com/aaron-lau-vTlVVCdSzSQ-unsplash.jpg',
     title: 'ChinaTown at nighttime, SF ',
     caption: 'Walked through ChinaTown at night, enjoying the lit streets and its added ambience.',
     createdAt: new Date(),
     updatedAt: new Date(),
    },
    {
     userId: 1,
     locationId: null,
     imgURL: 'https://touristrbucket.s3.us-west-1.amazonaws.com/albert-dera-K5zl0d-fhIM-unsplash.jpg',
     title: "Lover's Lane Trail at Presidio, SF ",
     caption: "What a beautiful sight. I could still enjoy the scenery without a lover :). Will definitely be taking my future partner here.",
     createdAt: new Date(),
     updatedAt: new Date(),
    },
    {
      userId: 1,
      locationId: null,
      imgURL: 'https://touristrbucket.s3.us-west-1.amazonaws.com/amogh-manjunath-HksFlo1t8iA-unsplash.jpg',
      title: "Riding into the sunset, downtown SF",
      caption: 'Yes, I had to chase the trolley. It was worth the shot.',
      createdAt: new Date(),
      updatedAt: new Date(),
     },
     {
      userId: 1,
      locationId: null,
      imgURL: 'https://touristrbucket.s3.us-west-1.amazonaws.com/braden-collum-AFlG5jpMvYg-unsplash.jpg',
      title: 'Snake street, Lombard Street SF',
      caption: 'Students should take their DMV test here. Joke aside, a great place for a run, no need to worry about cars :)',
      createdAt: new Date(),
      updatedAt: new Date(),
     },
     {
      userId: 1,
      locationId: null,
      imgURL: 'https://touristrbucket.s3.us-west-1.amazonaws.com/eberhard-grossgasteiger-g5487il35P0-unsplash.jpg',
      title: 'City lights, Twin Peaks SF',
      caption: 'I visit Twin Peaks every night. Becareful of cars racing down the slope when you come here. Otherwise, great place to hangout with friends or a special someone during the Summer.',
      createdAt: new Date(),
      updatedAt: new Date(),
     },
     {
      userId: 1,
      locationId: null,
      imgURL: 'https://touristrbucket.s3.us-west-1.amazonaws.com/howie-mapson-oXLWWfNSk-w-unsplash.jpg',
      title: 'The Palace of Fine Arts, SF',
      caption: 'Walked here for a peace of mind after work.',
      createdAt: new Date(),
      updatedAt: new Date(),
     },{
      userId: 1,
      locationId: null,
      imgURL: 'https://touristrbucket.s3.us-west-1.amazonaws.com/jack-patrick-a3ZPAE2kaGU-unsplash.jpg',
      title: 'Hipster men crossing',
      caption: 'Everyone, meet the techies of SF.',
      createdAt: new Date(),
      updatedAt: new Date(),
     },{
      userId: 1,
      locationId: null,
      imgURL: 'https://touristrbucket.s3.us-west-1.amazonaws.com/jonas-vandermeiren-CI_Dg3r3FM8-unsplash.jpg',
      title: 'A regular gloomy day at the pier, SF',
      caption: 'A rare occurence when this place is empty. Tea is great for a day like this.',
      createdAt: new Date(),
      updatedAt: new Date(),
     },{
      userId: 1,
      locationId: null,
      imgURL: 'https://touristrbucket.s3.us-west-1.amazonaws.com/kae-ng-e_uTO3fLmvk-unsplash.jpg',
      title: 'ChinaTown entrance, SF',
      caption: 'The iconic entrance to ChinaTown. On my way to Dim Sum.',
      createdAt: new Date(),
      updatedAt: new Date(),
     },{
      userId: 1,
      locationId: null,
      imgURL: 'https://touristrbucket.s3.us-west-1.amazonaws.com/kimberly-sterling-3AAyCMU5Ufg-unsplash.jpg',
      title: 'Houses',
      caption: 'Just admiring the uniqueness of SF architecture.',
      createdAt: new Date(),
      updatedAt: new Date(),
     },{
      userId: 1,
      locationId: null,
      imgURL: 'https://touristrbucket.s3.us-west-1.amazonaws.com/kyle-glenn-P5_ubLgnfv0-unsplash.jpg',
      title: 'Dutch Windmill at Golden Gate Park, SF',
      caption: "Didn't know this was here and I lived here for 4 years. Definitely a pleasant surprise.",
      createdAt: new Date(),
      updatedAt: new Date(),
     },{
      userId: 1,
      locationId: null,
      imgURL: 'https://touristrbucket.s3.us-west-1.amazonaws.com/meric-dagli-DtCEcY1k_qE-unsplash.jpg',
      title: 'Pier 7, SF',
      caption: 'Definitely took a big hit to the bank account to rent a boat for this shot. But definitely worth. #forTouristr',
      createdAt: new Date(),
      updatedAt: new Date(),
     },{
      userId: 1,
      locationId: null,
      imgURL: 'https://touristrbucket.s3.us-west-1.amazonaws.com/patrick-perkins-zGsDOJk6jR4-unsplash.jpg',
      title: 'People watching at Dolores Park, SF',
      caption: 'Enjoying a picnic with a group of friends at Dolores on a nice Saturday afternoon. Can you spot the hipsters, techies, art students?',
      createdAt: new Date(),
      updatedAt: new Date(),
     },{
      userId: 1,
      locationId: null,
      imgURL: 'https://touristrbucket.s3.us-west-1.amazonaws.com/photo-1562010018-de43d8ef0f30.webp',
      title: 'A lighted City Hall, SF',
      caption: 'Thank you whoever who did this.',
      createdAt: new Date(),
      updatedAt: new Date(),
     },{
      userId: 1,
      locationId: null,
      imgURL: 'https://touristrbucket.s3.us-west-1.amazonaws.com/photo-1565284851077-c1968950a2a1.webp',
      title: 'Cars on Lombardo St, SF',
      caption: "That white car is going up the opposite direction? I'm concerned.",
      createdAt: new Date(),
      updatedAt: new Date(),
     },{
      userId: 1,
      locationId: null,
      imgURL: 'https://touristrbucket.s3.us-west-1.amazonaws.com/photo-1584991845594-51b3bcdc0d14.webp',
      title: 'An unlighted City Hall, SF',
      caption: 'I think City Hall looks better lighted up at night or during pride.',
      createdAt: new Date(),
      updatedAt: new Date(),
     },{
      userId: 1,
      locationId: null,
      imgURL: 'https://touristrbucket.s3.us-west-1.amazonaws.com/photo-1616427816105-fc0b334bd6e6.webp',
      title: 'SF street',
      caption: 'Just something about this that I needed to take a pic of.',
      createdAt: new Date(),
      updatedAt: new Date(),
     },{
      userId: 1,
      locationId: null,
      imgURL: 'https://touristrbucket.s3.us-west-1.amazonaws.com/photo-1616912059100-05fe643ee63d.webp',
      title: 'Golden Gate Bridge, SF',
      caption: 'The classic bridge. Took this at Fort Mason.',
      createdAt: new Date(),
      updatedAt: new Date(),
     },{
      userId: 1,
      locationId: null,
      imgURL: 'https://touristrbucket.s3.us-west-1.amazonaws.com/photo-1619517402079-535aec4125d6.webp',
      title: 'Mural painted on a Mission St building, SF',
      caption: "My favorite district, the Mission. The best food comes from the mom and pops restaurant here.",
      createdAt: new Date(),
      updatedAt: new Date(),
     },{
      userId: 1,
      locationId: null,
      imgURL: 'https://touristrbucket.s3.us-west-1.amazonaws.com/photo-1621606016505-f74ee91fc522.webp',
      title: 'The Castro, SF',
      caption: 'I go here every weekend to dance the night away.',
      createdAt: new Date(),
      updatedAt: new Date(),
     },{
      userId: 1,
      locationId: null,
      imgURL: 'https://touristrbucket.s3.us-west-1.amazonaws.com/rich-hay-V0YpBGGk-_A-unsplash.jpg',
      title: 'Industrial bridge, SF',
      caption: 'I risked my life for this shot. Give likes!',
      createdAt: new Date(),
      updatedAt: new Date(),
     },{
      userId: 1,
      locationId: null,
      imgURL: 'https://touristrbucket.s3.us-west-1.amazonaws.com/sand-crain-ehwWojSyaB8-unsplash.jpg',
      title: 'Picnics at Presidio, SF',
      caption: 'Come here after my 9 to 5 corporate job. Bring your own food, the food here is a bit overpriced to be honest.',
      createdAt: new Date(),
      updatedAt: new Date(),
     },

  ], {});
  },
  down: (queryInterface, Sequelize) => {
    return queryInterface.bulkDelete('Photos', null, {});
  }
};
